"""Ensure created_at exists

Revision ID: b752f241f0a0
Revises: 
Create Date: 2024-09-21 09:18:50.933732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b752f241f0a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_user_id', table_name='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payments_user_id', 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###
